---
title: "Hydrologic data for use in calculating flow condition metrics for waters in and near National Park Service units."
subtitle: "Periods of record through the end of the 2018 Water Year"
author: "Joe DeVivo"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  word_document:
    df_print: kable
    fig_caption: yes
    fig_height: 5
    fig_width: 5
    highlight: haddock
    reference_docx: "common/NRDS_Author_Template_V3.2.docx"
  html_document:
    df_print: kable
    fig_caption: yes
    dev: svg
    highlight: haddock
    keep_md: yes
    smart: no
    theme: journal
    toc: yes
    toc_float: true
    number_sections: true
  pdf_document:
    toc: yes
    df_print: kable
    highlight: haddock
    lang: en
    keep_md: yes
    documentclass: article
editor_options:
  chunk_output_type: inline
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
link-citations: yes
params:
  projectDir: "N:/ESHydrology2"
---

<style type="text/css">

blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 14px;
    border-left: 5px solid #eee;
}
</style>

```{r setup, include=FALSE}

# This setup code loads both reproducible reporting packages
# (delete those not needed) and packages for the actual project.
# Note that it also generates the start of a BibTex literature cited
# including the citations for R and all used packages

# reproducible reporting packages
RRpackages <- c('markdown',     # links to Sundown rendering library
                'rmarkdown',    # newer rendering via pandoc
                'pander',       # alternative renderer for markdown,
                                # plus better tables than just knitr
                'knitr',
                "dataMaid",     # for makeCodebooks
                "R.rsp",        # dynamic generation of scientific reports
                "kimisc",       #
                "papeR",        # stat tables
                "texreg",       # formatting regression results for LaTeX
                                # or html
                "rmdHelpers",   # misc from Mark Peterson
                                #  thisFileName() thisFile_knit()
                'yaml',         # format data into markdown
                'rmdformats',   # templates including automatic ToC,
                                # also use_bookdown()
                'htmltools',    #
                "bibtex",
                "RefManageR",   # BibTeX reference manager
                "knitcitations" #
                )

inst <- RRpackages %in% installed.packages()
if (length(RRpackages[!inst]) > 0) {
   install.packages(RRpackages[!inst], dep = TRUE)
}
lapply(RRpackages, library, character.only = TRUE)

# __________________________________
# Now repeat for packages used in the analyses
pkgList <- c("devtools",
             "RODBC", 
             "EML",
             "EMLassemblyline",
             "dplyr")
inst <- pkgList %in% installed.packages()
if (length(pkgList[!inst]) > 0) {
   install.packages(pkgList[!inst], dep = TRUE, 
                    repos = "https://cloud.r-project.org")
}

lapply(pkgList, library, character.only = TRUE, quietly = TRUE)

# create stub of citations for packages
pkgBibTex <- lapply(c("base", pkgList, RRpackages), citation)

# pkgBibTex <- do.call()

knitr::opts_chunk$set(
   root.dir = params$projectDir,  # from YAML parameter, knitr instead of setwd()
   echo = TRUE,
   comment = " ",
#   dev = "svg",
   fig.path = "figures/",
   tidy.opts = list(width.cutoff = 60),
   tidy = TRUE
   )
# if ggplot, update theme to default to centered titles
if ("ggplot2" %in% .packages()) {
   theme_update(plot.title = element_text(hjust = 0.5))
}

#functions

```

```{r ReadData, include=FALSE}
# The following reads data files from the data subdirectories



```



# Abstract


# Background and Summary


# Methods


# Results


# Discussion


# Data Records


Table 4. Overview of data sets and their provenance.
```{r DataProvenanceTable, echo=FALSE}




```


# Data Quality Evaluation


# Usage Notes


# References


\pagebreak
# Appendix A. R Code Listing
```{r Listing, ref.label=knitr::all_labels() ,echo=TRUE, eval=FALSE}
```
# Appendix B. R Session and Version Information
```{r session-info, cache=FALSE}
sessionInfo()
Sys.time()
```


