#' Get DS References for a park-species combination
#'
#' \code{createProject} sets up all the directories needed when initializing a new project and copies a number of
#' template files to the new project directory if they do not already exist. This includes a blank RMD file template
#' with suggested packages to use for reproducible reporting and semi-automated generation of eml metadata files.
#'
#'
#' @param projectName A project name that can will be used as a part of file names generated by the template.
#'
#' @examples
#' createProject("New_Project")

createProject <-function(projectName){

# Create Directory Structure

if (!file.exists("data")){
  dir.create(file.path("data"))
}

if (!file.exists("data/raw")){
  dir.create(file.path("data/raw"))
}

if (!file.exists("data/temp")){
  dir.create(file.path("data/temp"))
}

if (!file.exists("data/processed")){
  dir.create(file.path("data/processed"))
}

if (!file.exists("common")){
  dir.create(file.path("common"))
}

if (!file.exists("dataPackages")){
  dir.create(file.path("dataPackages"))
}

if (!file.exists("dataPackages/CoreTemplates")){
  dir.create(file.path("dataPackages/CoreTemplates"))
}

if (!file.exists("output")){
  dir.create(file.path("output"))
}

if (!file.exists("figures")){
  dir.create(file.path("figures"))
}

if (!file.exists("metadata")){
  dir.create(file.path("metadata"))
}

# Copy template files from IMDReortTemplate package into new project directories


}
