#' Get DS References for a park-species combination
#'
#' \code{setupNewDataPackage} sets up all the directories and template files needed when creating a new data package. The
#' script requires the use of the EMLassembleyline package to generate the templates, and then overwrites the standard files
#' with IMD-specific versions to use as a starting point.
#'
#'
#' @param dataPackageName A project name that can will be used as a part of file names generated by the template.
#'
#' @examples
#' setupNewDataPackage("Package_Name")

setupNewDataPackage <-function(packageName){

  pkgList <- c("EMLassemblyline")

  inst <- pkgList %in% installed.packages()
  if (length(pkgList[!inst]) > 0) {
    install.packages(pkgList[!inst], dep = TRUE,
                     repos = "https://cloud.r-project.org")
  }

  lapply(pkgList, library, character.only = TRUE, quietly = TRUE)

  # create template files from EMLassemblyline package

  template_directories(
    path = 'dataPackages/',
    dir.name = packageName
  )

  template_core_metadata(
    path = paste0('dataPackages/', packageName, '/metadata_templates'),
    license = 'CC0'
  )

  # update template files with IMD specific versions

  metadata_templates<-list.files(paste0(templateDir,"CoreTemplates/metadata_templates"))
  metadata_templatesSource<-paste0(templateDir,"CoreTemplates/metadata_templates/", metadata_templates)
  metadata_templatesDest<-paste0("dataPackages/",packageName,"/metadata_templates/")


  file.copy(metadata_templatesSource,metadata_templatesDest,overwrite = TRUE)

  file.copy(paste0(templateDir,"CoreTemplates/run_EMLassemblyline_Templates.R"),
            paste0("dataPackages/", packageName,"/run_EMLassemblyline_for_",packageName,".R"),overwrite = TRUE)

}
